<?php
if(!defined('MYSQL_HOST'))
{
	define('MYSQL_HOST','localhost');
}
if(!defined('MYSQL_USER'))
{
	define('MYSQL_USER','root');
}
if(!defined('MYSQL_PASSWORD'))
{
	define('MYSQL_PASSWORD','');
}
if(!defined('MYSQL_DB'))
{
	define('MYSQL_DB','demo');
}
if(!defined('TEMP_DIR'))
{
	define('TEMP_DIR','C:\xampp\htdocs\Demo\img');
}
?>